### In this notebook, we will build a movie recommender system using Cosine Similarity algorithm.

Mount the google drive to access dataset stored in it.

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


Import required libraries
1. Pandas - open source data analysis and manipulation tool
2. Numpy - 

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
movies = pd.read_csv('/content/gdrive/MyDrive/movie_dataset.csv')
movies

index  ...           director
0         0  ...      James Cameron
1         1  ...     Gore Verbinski
2         2  ...         Sam Mendes
3         3  ...  Christopher Nolan
4         4  ...     Andrew Stanton
...     ...  ...                ...
4798   4798  ...   Robert Rodriguez
4799   4799  ...       Edward Burns
4800   4800  ...        Scott Smith
4801   4801  ...        Daniel Hsia
4802   4802  ...   Brian Herzlinger

[4803 rows x 24 columns]

In [6]:
features = ['keywords', 'cast', 'genres', 'director']

for feat in features:
    movies[feat] = movies[feat].fillna('')

In [7]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
movies["combined_features"] = movies.apply(combined_features, axis =1)

In [8]:
movies

index  ...                                  combined_features
0         0  ...  culture clash future space war space colony so...
1         1  ...  ocean drug abuse exotic island east india trad...
2         2  ...  spy based on novel secret agent sequel mi6 Dan...
3         3  ...  dc comics crime fighter terrorist secret ident...
4         4  ...  based on novel mars medallion space travel pri...
...     ...  ...                                                ...
4798   4798  ...  united states\u2013mexico barrier legs arms pa...
4799   4799  ...   Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800   4800  ...  date love at first sight narration investigati...
4801   4801  ...   Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802   4802  ...  obsession camcorder crush dream girl Drew Barr...

[4803 rows x 25 columns]

In [9]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(movies["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
cosine_sim = cosine_similarity(count_matrix)

In [11]:
cosine_sim

array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

Notes:

Recommender systems are an important class of machine learning algorithms that offer “relevant” suggestions to users.

Youtube, Amazon, Netflix, all function on recommendation systems where the system recommends you the next video or product based on your past activity (Content-based Filtering) or based on activities and preferences of other users similar to you (Collaborative Filtering).

Recommendation Systems work based on the similarity between either the content or the users who access the content.

There are several ways to measure the similarity between two items. The recommendation systems use this similarity matrix to recommend the next most similar product to the user.